### ISSUE TITLE
Do initial "intake"

### ISSUE THREAD

**Issue by jaredh159** [friends-library/william-caton#1]
### Source Libre Office docs:

* [Original](https://cp.sync.com/dl/02f856ff0/rutztgip-cadir5cn-a5kwq69d-jrgwz36x)
* [Modernized](https://cp.sync.com/dl/265aefab0/7bp5vw25-7f678rts-vj3gk83a-cjrmykut)

## Original book scans

* [Book Scan #1](https://books.google.com/books?id=79lKAQAAMAAJ&pg=PA435#v=onepage&q&f=false)

**Comment by juliegugge** [comment]
yeah I thought it looked like you'd given Caton to Kiah! But I don't know github enough so I started him anyway. Hope that didn't cause any problems.
